# twitter/finatra sbt build/test with coverage
name: sbt-build

env:
  JAVA_OPTS: "-Dsbt.log.noformat=true"
  SKIP_FLAKY_TRAVIS: "true"
defaults:
  run:
    shell: bash
on:
  push:
    branches: [ ccoco/WorkflowBuild ]

jobs:
  dodo-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [openjdk@1.8]
        scala: [2.11.12, 2.12.8, 2.13.1]
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - name: cache/maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: cache/ivy2-cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref }}-sbt-ivy-cache-
      - name: cache/ivy2-local
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/com.twitter
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref }}-sbt-ivy-local-
      - name: cache/dodo
        uses: actions/cache@v1
        with:
          path: ~/.dodo
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref }}-dodo-
      - name: dodo
        run: |
          curl -s https://raw.githubusercontent.com/twitter/dodo/develop/bin/build | bash -s -- --no-test --scala-version ${{ matrix.scala }} finatra
  test-with-coverage: # generate coverage report for 2.12.8 on jdk1.8
    needs: dodo-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [openjdk@1.8, openjdk@1.11]
        scala: [2.12.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - name: cache/maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: cache/ivy2-cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref }}-sbt-ivy-cache-
      - name: cache/ivy2-local
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/com.twitter
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref }}-sbt-ivy-local-
      - name: cache/sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-${{ matrix.java }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: test
        if: ${{ matrix.java != 'openjdk@1.8' }}
        run: |
          ./sbt ++${{ matrix.scala }} clean test
      - name: test/with-coverage
        if: ${{ matrix.java == 'openjdk@1.8' }}
        run: |
          ./sbt ++${{ matrix.scala }} clean coverage test coverageReport
      - name: test/coverage-report/generate
        if: ${{ matrix.java == 'openjdk@1.8' }}
        run: |
          ./sbt ++${{ matrix.scala }} coverageAggregate
      - name: test/coverage-report/upload
        if: ${{ success() && matrix.java == 'openjdk@1.8' }}
        uses: codecov/codecov-action@v1
  test:
    needs: dodo-build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        java: [openjdk@1.8, openjdk@1.11]
        scala: [2.11.12]
        experimental: [false]
        include:
          - scala: 2.13.1
            java: openjdk@1.8
            experimental: true
          - scala: 2.13.1
            java: openjdk@1.11
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java }}
      - name: cache/maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: cache/ivy2-cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref }}-sbt-ivy-cache-
      - name: cache/ivy2-local
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/local/com.twitter
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref }}-sbt-ivy-local-
      - name: cache/sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-${{ matrix.java }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: test
        run: |
          ./sbt ++${{ matrix.scala }} clean test
